#!/usr/bin/env bash

controller="E0:D4:64:01:AE:F4"
device="7C:96:D2:8E:1F:BF"

status=$(bluetoothctl show ${controller} | grep Powered | awk '{printf "%s", $2}')

if [ ${status} = "yes" ]; then
  printf "{\"name\":\"bluetooth\",\"instance\":\"status\",\"full_text\":\"bluetooth: ${status}\",\"color\":\"#00ff00\"}"
else
  printf "{\"name\":\"bluetooth\",\"instance\":\"status\",\"full_text\":\"bluetooth: ${status}\",\"color\":\"#ff0000\"}"
fi

for device in $(bluetoothctl devices | awk '{print $2}'); do
  bluetoothctl info "${device}" | grep Connected | grep "yes" 2>&1 1>/dev/null
  res=$?
  if [[ ${res} -eq 0 ]]; then
    name=$(bluetoothctl info "${device}" | grep Alias | awk '{printf "%s", $2}')
    printf ",{\"name\":\"device\",\"instance\":\"status\",\"full_text\":\"device: ${name}\",\"color\":\"#ffffff\"}"
  fi
done
