#!/usr/bin/env bash

val=$(pulseaudio-ctl full-status | awk '{printf("%s",($3 == "yes" ? "mute" : "unmute"))}')

if [ ${val} = "mute" ]; then
  printf "{\"name\":\"mic\",\"instance\":\"status\",\"full_text\":\"mic: ${val}\",\"color\":\"#ff0000\"}"
else
  printf "{\"name\":\"mic\",\"instance\":\"status\",\"full_text\":\"mic: ${val}\",\"color\":\"#00ff00\"}"
fi
