#!/usr/bin/env bash

val=$(pactl list sink-inputs | grep "media.name" | awk -F'"' '{print $2}' | sed -e 's/ - YouTube Music//')

printf "{\"name\":\"playing\",\"instance\":\"status\",\"full_text\":\"🎵: ${val}\",\"color\":\"#b9b9b9\"}"
